replace_relation = {
	'cabinet ': 'cabinet',
	'table ': 'table',
	'trash can': 'trashcan',
	'curtain ': 'curtain',
	'curtainw': 'curtain',
	'closestool': 'closetool',
	'stoolz': 'stool',
	'bed ': 'bed',
	'sf ': 'sofa',
	'DT ': 'carpet',
	'closeddoor': 'closedoor',
	'DX ': 'wire',
	'sofafeces': 'feces',
	'fecesstool': 'stool',
	'carpetsofa': 'sofa',
	'分': 'sofa',
	'DT': 'carpet',
	'出来 ': 'curtain',
	'出来': 'curtain',
	'sf': 'sofa',
	'本地': 'sofa',
	'发展': 'cabinet',
	'carpetcabinet': 'cabinet',
	'cabinettrashcan': 'trashcan',
	'wirecabinet': 'cabinet',
	'sockscabinet': 'cabinet'
}

shujut_relation = {
	'pets': 'petfeces',
	'petfeces': 'feces',
	'soy sauce or vinegar': 'stains',
	'milk': 'stains',
	'coffee': 'stains',
	'tea': 'stains',
	'porridge': 'stains',
	'trash can': 'trashcan',
	'trashbin': 'trashcan',
	'trash_can': 'trashcan',
	'trash': 'trashcan',
	'socks': 'clothes',
}
